[build]
command = "npm start"
publish = "C:\Users\mdh05\Documents\skillspire\expense-tracker\server" # Change this to your server's build output

[build.environment]
NODE_VERSION = "18.13.0" # Change this to your desired Node.js version